name: CMLPR Corp

markdown: rdiscount
#markdown: kramdown

permalink: /blog/:year/:month/:day/:title

# For code highlighting
highlighter: pygments

# For MATH formulations
kramdown:
  input: GFM

# SiteMaps
gems:
  - jekyll-sitemap

# Search Engine Optimziation
gems:
  - jekyll-seo-tag


# Sass folder, to compress the imported Bootstrap files
sass:
    sass_dir: _sass
    style: :compressed
