name: CMLPR Corp
title: CMLPR Corp
description: CMLPR

tagline: About Everything
author :
  name : CMLPR
  email : cmlpr@outlook.com

#markdown: rdiscount # not supported by github
markdown: kramdown

permalink: /blog/:year/:month/:day/:title

# For code highlighting
#highlighter: pygments # not supported by github
highlighter: rouge

# For MATH formulations
kramdown:
  input: GFM

# SiteMaps
# Search Engine Optimziation
# RSS feed
gems:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap

# Sass folder, to compress the imported Bootstrap files
sass:
    sass_dir: _sass
    style: :compressed

# Post excerpt
excerpt_separator: <!--more-->


# Pagination
# Maximum number of posts per page
# If a site has 12 posts and specifies paginate: 5, 
# Jekyll will write blog/index.html with the first 5 posts, 
# blog/page2/index.html with the next 5 posts and 
# blog/page3/index.html with the last 2 posts into the destination directory.
paginate: 5
paginate_path: "/blog/page:num/"

categories_path : /blog/categories.html
tags_path : /blog/tags.html