name: CMLPR Corp
title: CMLPR Corp
description: CMLPR

tagline: About Everything
author :
  name : CMLPR
  email : cmlpr@outlook.com

markdown: rdiscount
#markdown: kramdown

permalink: /blog/:year/:month/:day/:title

# For code highlighting
highlighter: pygments

# For MATH formulations
kramdown:
  input: GFM

# SiteMaps
# Search Engine Optimziation
# RSS feed
gems:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed

# Sass folder, to compress the imported Bootstrap files
sass:
    sass_dir: _sass
    style: :compressed
